// <auto-generated />
using System;
using Data.Configuration.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Configuration.Migrations.LogDb
{
    [DbContext(typeof(LogDbContext))]
    partial class LogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("applicationId");

                    b.Property<string>("Callsite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("callsite");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exception");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level");

                    b.Property<DateTime>("Logged")
                        .HasColumnType("datetime2")
                        .HasColumnName("logged");

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logger");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hostname");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("properties");

                    b.HasKey("Id");

                    b.ToTable("log", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationId = 2,
                            Level = "ERROR",
                            Logged = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineName = "HOST1",
                            Message = ""
                        },
                        new
                        {
                            Id = 2,
                            ApplicationId = 1,
                            Level = "FATAL",
                            Logged = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineName = "HOST2",
                            Message = ""
                        },
                        new
                        {
                            Id = 3,
                            ApplicationId = 2,
                            Level = "WARNING",
                            Logged = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineName = "HOST3",
                            Message = ""
                        },
                        new
                        {
                            Id = 4,
                            ApplicationId = 1,
                            Level = "FATAL",
                            Logged = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineName = "HOST4",
                            Message = ""
                        },
                        new
                        {
                            Id = 5,
                            ApplicationId = 2,
                            Level = "ERROR",
                            Logged = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineName = "HOST5",
                            Message = ""
                        },
                        new
                        {
                            Id = 6,
                            ApplicationId = 1,
                            Level = "WARNING",
                            Logged = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineName = "HOST6",
                            Message = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
